# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/hedi/.cmake/bin/cmake

# The command to remove a file.
RM = /home/hedi/.cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hedi/Documents/DNA_PredatorPrey

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hedi/Documents/DNA_PredatorPrey

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/hedi/.cmake/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/hedi/.cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hedi/Documents/DNA_PredatorPrey/CMakeFiles /home/hedi/Documents/DNA_PredatorPrey/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hedi/Documents/DNA_PredatorPrey/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named predatorPrey

# Build rule for target.
predatorPrey: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predatorPrey
.PHONY : predatorPrey

# fast build rule for target.
predatorPrey/fast:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/build
.PHONY : predatorPrey/fast

src/PdeSystem/cudaComputer.o: src/PdeSystem/cudaComputer.cu.o

.PHONY : src/PdeSystem/cudaComputer.o

# target to build an object file
src/PdeSystem/cudaComputer.cu.o:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/cudaComputer.cu.o
.PHONY : src/PdeSystem/cudaComputer.cu.o

src/PdeSystem/cudaComputer.i: src/PdeSystem/cudaComputer.cu.i

.PHONY : src/PdeSystem/cudaComputer.i

# target to preprocess a source file
src/PdeSystem/cudaComputer.cu.i:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/cudaComputer.cu.i
.PHONY : src/PdeSystem/cudaComputer.cu.i

src/PdeSystem/cudaComputer.s: src/PdeSystem/cudaComputer.cu.s

.PHONY : src/PdeSystem/cudaComputer.s

# target to generate assembly for a file
src/PdeSystem/cudaComputer.cu.s:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/cudaComputer.cu.s
.PHONY : src/PdeSystem/cudaComputer.cu.s

src/PdeSystem/predator_prey_system.o: src/PdeSystem/predator_prey_system.cpp.o

.PHONY : src/PdeSystem/predator_prey_system.o

# target to build an object file
src/PdeSystem/predator_prey_system.cpp.o:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/predator_prey_system.cpp.o
.PHONY : src/PdeSystem/predator_prey_system.cpp.o

src/PdeSystem/predator_prey_system.i: src/PdeSystem/predator_prey_system.cpp.i

.PHONY : src/PdeSystem/predator_prey_system.i

# target to preprocess a source file
src/PdeSystem/predator_prey_system.cpp.i:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/predator_prey_system.cpp.i
.PHONY : src/PdeSystem/predator_prey_system.cpp.i

src/PdeSystem/predator_prey_system.s: src/PdeSystem/predator_prey_system.cpp.s

.PHONY : src/PdeSystem/predator_prey_system.s

# target to generate assembly for a file
src/PdeSystem/predator_prey_system.cpp.s:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/predator_prey_system.cpp.s
.PHONY : src/PdeSystem/predator_prey_system.cpp.s

src/PdeSystem/predator_prey_system_gpu.o: src/PdeSystem/predator_prey_system_gpu.cpp.o

.PHONY : src/PdeSystem/predator_prey_system_gpu.o

# target to build an object file
src/PdeSystem/predator_prey_system_gpu.cpp.o:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/predator_prey_system_gpu.cpp.o
.PHONY : src/PdeSystem/predator_prey_system_gpu.cpp.o

src/PdeSystem/predator_prey_system_gpu.i: src/PdeSystem/predator_prey_system_gpu.cpp.i

.PHONY : src/PdeSystem/predator_prey_system_gpu.i

# target to preprocess a source file
src/PdeSystem/predator_prey_system_gpu.cpp.i:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/predator_prey_system_gpu.cpp.i
.PHONY : src/PdeSystem/predator_prey_system_gpu.cpp.i

src/PdeSystem/predator_prey_system_gpu.s: src/PdeSystem/predator_prey_system_gpu.cpp.s

.PHONY : src/PdeSystem/predator_prey_system_gpu.s

# target to generate assembly for a file
src/PdeSystem/predator_prey_system_gpu.cpp.s:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/PdeSystem/predator_prey_system_gpu.cpp.s
.PHONY : src/PdeSystem/predator_prey_system_gpu.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/predatorPrey.dir/build.make CMakeFiles/predatorPrey.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... predatorPrey"
	@echo "... edit_cache"
	@echo "... src/PdeSystem/cudaComputer.o"
	@echo "... src/PdeSystem/cudaComputer.i"
	@echo "... src/PdeSystem/cudaComputer.s"
	@echo "... src/PdeSystem/predator_prey_system.o"
	@echo "... src/PdeSystem/predator_prey_system.i"
	@echo "... src/PdeSystem/predator_prey_system.s"
	@echo "... src/PdeSystem/predator_prey_system_gpu.o"
	@echo "... src/PdeSystem/predator_prey_system_gpu.i"
	@echo "... src/PdeSystem/predator_prey_system_gpu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

